### ISSUE TITLE
Code review by team 45- Helliums

### ISSUE THREAD

**Issue by Oitur** [euqueme/enumerable-methods#1]
Hello Maria
Good work so far!

I'm suggesting that you review the git flow you're using so that you can mantain a structure of master -> development - > feature_branch, as it's a good way to maintain your git repository.

You might want to use some test cases to see if your code is returning the same thing as the original ruby method. Remember to comment it before comitting it.

**Comment by euqueme** [comment]
Thank you so much for the review.

I did the changes on the git-flow as you can [see](https://github.com/euqueme/enumerable-methods)

Also, I have my test cases [here](https://repl.it/@MariaEugeniaEu2/liveEnumerables)´

So I'm closing this, thanks again!
